arch:
  - arm64

language: rust
rust:
  - nightly

script:
  - make spectests-singlepass
  - make release-singlepass
  - make wapm
  - make build-install
  - cp ./wasmer.tar.gz ./artifacts/$(./scripts/binary-name.sh)

stage: GitHub Release
  script: echo "Deploying to GitHub releases ..."
  deploy:
    provider: releases
    file_glob: true
    file: artifacts/*
    api_key: $GITHUB_OAUTH_TOKEN
    # This is set to the previous artifacts are not deleted by travis
    skip_cleanup: true

addons:
  apt:
    packages:
      - cmake

branches:
  only:
  - feature/singlepass-aarch64