language: rust
cache: cargo
rust:
  - nightly
env:
  - CARGO_INCREMENTAL=1
os: linux
sudo: false
notifications:
  email:
    on_success: never
    on_failure: change
script:
  - cargo test
  # - cargo bench
