[package]
name = "wasmer"
version = "0.1.0"
authors = ["Syrus Akbary <me@syrusakbary.com>"]
edition = "2018"
repository = "https://github.com/wapmio/wasmer"
publish = false

[dependencies]
cranelift-codegen = "0.20.0"
cranelift-entity = "0.20.1"
cranelift-wasm = "0.20.1"
cranelift-native = "0.20.0"
docopt = "1.0.0"
serde = "1.0.55"
serde_derive = "1.0.55"
tempdir = "*"
error-chain = "0.12.0"
structopt = "0.2.11"
wabt = "0.6.0"
wasmparser = "0.20.0"
region = "0.3.0"
memmap = "0.6.2"
target-lexicon = "0.0.3"
