[package]
name = "wasmer-bin"
version = "0.16.2"
authors = ["The Wasmer Engineering Team <engineering@wasmer.io>"]
repository = "https://github.com/wasmerio/wasmer"
description = "High-Performance WebAssembly Framework"
license = "MIT"
include = [
    "src/**/*",
    "Cargo.lock",
    "Cargo.toml",
    "LICENSE",
    "Makefile",
    "/README.md"
]
readme = "README.md"
edition = "2018"
default-run = "wasmer"
publish = false
autoexamples = false

[dependencies]
wasmer = { version = "0.16.2", path = "lib/api", default-features = false }
wasmer-compiler = { version = "0.16.2", path = "lib/compiler" }
wasmer-compiler-cranelift = { version = "0.16.2", path = "lib/compiler-cranelift", optional = true }
wasmer-compiler-singlepass = { version = "0.16.2", path = "lib/compiler-singlepass", optional = true }
wasmer-compiler-llvm = { version = "0.16.2", path = "lib/compiler-llvm", optional = true }
wasmer-engine = { version = "0.16.2", path = "lib/engine" }
wasmer-engine-jit = { version = "0.16.2", path = "lib/engine-jit", optional = true }
wasmer-wasi = { version = "0.16.2", path = "lib/wasi", optional = true }
wasmer-wasi-experimental-io-devices = { version = "0.16.2", path = "lib/wasi-experimental-io-devices", optional = true }
wasmer-wast = { version = "0.16.2", path = "tests/lib/wast", optional = true }
wasmer-cache = { version = "0.16.2", path = "lib/cache", optional = true }
atty = "0.2"
colored = "1.9"
anyhow = "1.0.28"
structopt = { version = "0.3", features = ["suggestions"] }
# For the function names autosuggestion
distance = "0.4"
# For the inspect subcommand
bytesize = "1.0.0"

[workspace]
members = [
    "lib/c-api",
]

[build-dependencies]
test-generator = { path = "tests/lib/test-generator" }
anyhow = "1.0.28"
glob = "0.3"
rustc_version = "0.2"

[dev-dependencies]
anyhow = "1.0.28"
test-utils = { path = "tests/lib/test-utils" }

[features]
# Don't add the compiler features in default, please add them on the Makefile
# since we might want to autoconfigure them depending on the availability on the host.
default = ["wat", "wast", "wasi", "cranelift", "cache", "jit"]
engine = []
jit = [
    "wasmer-engine-jit",
    "engine",
]
cache = ["wasmer-cache"]
wast = ["wasmer-wast"]
wasi = ["wasmer-wasi"]
wat = ["wasmer/wat"]
compiler = ["wasmer-engine-jit/compiler",]
experimental-io-devices = [
    "wasmer-wasi-experimental-io-devices",
    "wasi"
]
singlepass = [
    "wasmer-compiler-singlepass",
    "test-utils/singlepass",
    "compiler",
]
cranelift = [
    "wasmer-compiler-cranelift",
    "test-utils/cranelift",
    "compiler",
]
llvm = [
    "wasmer-compiler-llvm",
    "test-utils/llvm",
    "compiler",
]

# [profile.release]
# lto  = "fat"
