[package]
name = "wasmer-bin"
version = "1.0.0-alpha.1"
authors = ["The Wasmer Engineering Team <engineering@wasmer.io>"]
repository = "https://github.com/wasmerio/wasmer"
description = "High-Performance WebAssembly Framework"
license = "MIT"
include = [
    "src/**/*",
    "Cargo.lock",
    "Cargo.toml",
    "LICENSE",
    "Makefile",
    "/README.md"
]
readme = "README.md"
edition = "2018"
default-run = "wasmer"
publish = false
autoexamples = false

[[bin]]
name = "wasmer"
path = "src/bin/wasmer.rs"
doc = false

[dependencies]
wasmer = { version = "1.0.0-alpha.1", path = "lib/api", default-features = false }
wasmer-compiler = { version = "1.0.0-alpha.1", path = "lib/compiler" }
wasmer-compiler-cranelift = { version = "1.0.0-alpha.1", path = "lib/compiler-cranelift", optional = true }
wasmer-compiler-singlepass = { version = "1.0.0-alpha.1", path = "lib/compiler-singlepass", optional = true }
wasmer-compiler-llvm = { version = "1.0.0-alpha.1", path = "lib/compiler-llvm", optional = true }
wasmer-emscripten = { version = "1.0.0-alpha.1", path = "lib/emscripten", optional = true }
wasmer-engine = { version = "1.0.0-alpha.1", path = "lib/engine" }
wasmer-engine-jit = { version = "1.0.0-alpha.1", path = "lib/engine-jit", optional = true }
wasmer-engine-native = { version = "1.0.0-alpha.1", path = "lib/engine-native", optional = true }
wasmer-wasi = { version = "1.0.0-alpha.1", path = "lib/wasi", optional = true }
wasmer-wasi-experimental-io-devices = { version = "1.0.0-alpha.1", path = "lib/wasi-experimental-io-devices", optional = true }
wasmer-wast = { version = "1.0.0-alpha.1", path = "tests/lib/wast", optional = true }
wasmer-cache = { version = "1.0.0-alpha.1", path = "lib/cache", optional = true }
wasm-common = { version = "1.0.0-alpha.1", path = "lib/wasm-common" }
atty = "0.2"
colored = "1.9"
anyhow = "1.0"
structopt = { version = "0.3", features = ["suggestions"] }
# For the function names autosuggestion
distance = "0.4"
# For the inspect subcommand
bytesize = "1.0"
cfg-if = "0.1"

[workspace]
members = [
    "lib/c-api",
]

[build-dependencies]
test-generator = { path = "tests/lib/test-generator" }
build-deps = "0.1.4"
anyhow = "1.0"
glob = "0.3"
rustc_version = "0.2"

[dev-dependencies]
anyhow = "1.0"
blake3 = "0.3"
criterion = "0.3"
lazy_static = "1.4"
wasmer-engine-dummy = { path = "tests/lib/engine-dummy" }

[features]
# Don't add the compiler features in default, please add them on the Makefile
# since we might want to autoconfigure them depending on the availability on the host.
default = [
    "wat",
    "wast",
    "jit",
    "native",
    "cache",
    "wasi",
    "emscripten",
]
engine = []
jit = [
    "wasmer-engine-jit",
    "engine",
]
native = [
    "wasmer-engine-native",
    "engine",
]
cache = ["wasmer-cache"]
wast = ["wasmer-wast"]
wasi = ["wasmer-wasi"]
emscripten = ["wasmer-emscripten"]
wat = ["wasmer/wat"]
compiler = [
    "wasmer-compiler/translator",
    "wasmer-engine-jit/compiler",
    "wasmer-engine-native/compiler"
]
experimental-io-devices = [
    "wasmer-wasi-experimental-io-devices",
    "wasi"
]
singlepass = [
    "wasmer-compiler-singlepass",
    "compiler",
]
cranelift = [
    "wasmer-compiler-cranelift",
    "compiler",
]
llvm = [
    "wasmer-compiler-llvm",
    "compiler",
]

# Testing features
test-singlepass = [
    "singlepass",
]
test-cranelift = [
    "cranelift",
]
test-llvm = [
    "llvm",
]

# [profile.release]
# lto  = "fat"

[[bench]]
name = "static_and_dynamic_functions"
harness = false

[[example]]
name = "engine-native"
path = "examples/engine_native.rs"
required-features = ["cranelift"]