[package]
name = "wasmer"
version = "0.1.0"
authors = ["Syrus Akbary <me@syrusakbary.com>"]
edition = "2018"
repository = "https://github.com/wapmio/wasmer"
publish = false

[dependencies]
cranelift-native = "0.22.0"
# cranelift-native = { path = "cranelift/lib/native" }
cranelift-codegen = "0.22.0"
# cranelift-codegen = { path = "cranelift/lib/codegen" }
cranelift-entity = "0.22.0"
# cranelift-entity = { path = "cranelift/lib/entity" }
cranelift-wasm = "0.22.0"
# cranelift-wasm = { path = "cranelift/lib/wasm" }
docopt = "1.0.0"
serde = "1.0.55"
serde_derive = "1.0.55"
tempdir = "*"
error-chain = "0.12.0"
structopt = "0.2.11"
wabt = "0.6.0"
wasmparser = "0.20.0"
region = "0.3.0"
memmap = "0.6.2"
spin = "0.4.9"
target-lexicon = { version = "0.0.3", default-features = false }
