[package]
name = "wasi-networking"
version = "0.1.0"
authors = ["Heyang Zhou <zhy20000919@hotmail.com>"]
edition = "2018"

[workspace]

[dependencies]
wasmer-kernel-net = { path = "../../lib/kernel-net" }