name: Release cloudcompiler.wasm

env:
  RUST_BACKTRACE: 1

on: 
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.59
          target: ${{ matrix.target }}
      - name: Install wasm32-wasi target
        shell: bash
        run: |
          rustup target add wasm32-wasi
      - name: Build cloudcompiler.wasm
        shell: bash
        run: |
          cargo build --release --target wasm32-wasi &&
          mkdir target/release/cloudcompiler &&
          cp target/release/wasmer.wasm target/release/cloudcompiler/cloudcompiler.wasm &&
          cat << EOF > target/release/cloudcompiler/wapm.toml
          [package]
          name = "${{ secrets.WAPM_DEV_USERNAME }}/cloudcompiler"
          version = "$(git tag | tail -n1)"
          description = "cloudcompiler.wasm"
          license = "MIT"
          repository = "https://github.com/wasmerio/wasmer"

          [[module]]
          name = "cloudcompiler"
          source = "cloudcompiler.wasm"
          abi = "wasi"

          [module.interfaces]
          wasi = "0.1.0-unstable"

          [[command]]
          name = "cloudcompiler"
          module = "cloudcompiler"
          EOF