# Separate workflow for the wasmer-web crate.
#

# Automatically cancel previous workflow runs when a new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Wasmer Web
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  web:
    name: Build and Test (wasmer-web)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly

    - name: Show Rust version
      run: |
        rustc --version

    - name: Check formatting
      shell: bash
      run: |
        cd lib/wasi-web
        cargo fmt --check

    - name: Check
      env:
        CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      run: |
        cd lib/wasi-web
        cargo check
