# Separate workflow for the wasmer-web crate.
#

name: Wasmer Web

on:
  push:
    branches:
      - main
  pull_request:

# Automatically cancel previous workflow runs when a new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

jobs:
  web:
    name: Build and Test (wasmer-web)
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: lib/wasi-web
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly-2023-05-25

    - name: Setup Chromedriver
      uses: nanasess/setup-chromedriver@v2

    - name: Show Rust version
      run: rustc --version --verbose

    - name: Check formatting
      shell: bash
      run: cargo fmt --check

    - name: Check
      run: cargo check --verbose --locked

    - name: Start Webpack Dev Server
      uses: JarvusInnovations/background-action@v1
      with:
        run: npm install && npm run dev
        working-directory: lib/wasmer-web
        wait-on: http://localhost:9000/

    - name: Browser Integration Tests
      run: cargo test --verbose --locked -- --test-threads=1
      working-directory: tests/wasi-web
